volumes:
  postgres_data:

services:
  postgres:
    image: postgres:13
    restart: unless-stopped
    environment:
      # - POSTGRES_USER # defaults to postgres
      POSTGRES_DB: keycloak # defaults to value of POSTGRES_USER
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: bitnami/keycloak:26.1.5
    depends_on:
      - postgres
    ports:
      - "0.0.0.0:8080:8080"
    volumes:
      - ./keycloak/providers/:/opt/bitnami/keycloak/providers/
    environment:
      KEYCLOAK_CREATE_ADMIN_USER: true
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KEYCLOAK_MANAGEMENT_USER: manager
      KEYCLOAK_MANAGEMENT_PASSWORD: password
      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: postgres
      KEYCLOAK_DATABASE_PASSWORD: password
      KEYCLOAK_DATABASE_SCHEMA: public
      ROCKATCHAT_BASE_URL: ${ROCKATCHAT_BASE_URL:-http://localhost:3000}
      ROCKATCHAT_AUTH_TOKEN: ${ROCKATCHAT_AUTH_TOKEN}
      ROCKATCHAT_USER_ID: ${ROCKATCHAT_USER_ID}
