name: Reusable build workflow

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package

      - name: Prepare staging directory
        run: |
          mkdir staging
          cp target/*shaded.jar staging/

      - name: Create hash files
        run: |
          for jar in *.jar
          do
              sha512sum $jar | awk '{ print $1 }' > "${jar}.sha512"
          done
        working-directory: staging

      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: staging
