name: Release

on:
  push:
    tags:
      - v**

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download built JARs
        uses: actions/download-artifact@v4
        with:
          name: packages
          path: staging

      - name: Create GitHub Release
        run: gh release create ${GITHUB_REF_NAME} staging/* --generate-notes --verify-tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
